### ISSUE TITLE
How do you make the buttons smaller?

### ISSUE THREAD

**Issue by liveaffiliates** [ceryle/SegmentedButton#1]
Hi,

Great library looks fantastic. I tried to use the library but I couldn't get it to work for anything other than having the width set to 0 and the weight for each set to 1.  how do you change the size of the buttons without is cutting of the radius edges?

Thanks

**Comment by ceryle** [comment]
Hello,
Thank you for the kind words. Currently what you want to achieve is not possible. SegmentedButtonGroup is actually a LinearLayout with its child's width 0 and weight 1. It takes the buttons in it and resizes them equally. In next release I will try to make it happen. Have a nice day.

**Comment by liveaffiliates** [comment]
Ok thank you for your help

**Comment by ceryle** [comment]
Making different sized buttons are now possible. I updated the library and also there are examples in sample project. New version is "v1.1.4'".
