### ISSUE TITLE
setEnabled() does not work

### ISSUE THREAD

**Issue by DonatelloX** [ceryle/SegmentedButton#11]
The SegmentedButton is a beautiful control for Android. In some cases, I would like to disable the control. But the setEnabled(false) command does not work.
Please, can someone help me?
Thank you
Regards,
Donatello

**Comment by ceryle** [comment]
Thank you Donatello. You can disable buttons with setClickable or setEnabled methods and also you can do the same thing in xml with android:clickable and sbg_enable attributes. Currently, there is no grayish disabled display when you setEnabled to false. However, I am planning to add it in next release.
