### ISSUE TITLE
setPosition(0,true) generates the event setOnClickedButtonPosition

### ISSUE THREAD

**Issue by DonatelloX** [ceryle/SegmentedButton#12]
When I use setPosition (), the setOnClickedButtonPosition event is fired but it should not happen.
Thank you
Regards,
Donatello

**Comment by ceryle** [comment]
Hi,
I will take a look at this and the other one you asked soon.

**Comment by ceryle** [comment]
Hi again,
setOnClickedButtonPosition() event is now fired if you click buttons. With other interface "onPositionChanged" which I have newly added, you can listen any position change that happens on the group.

**Comment by DonatelloX** [comment]
Hi ceryle,
Thank you! You are great!
Regards,
Donatello

**Comment by ceryle** [comment]
Your welcome, Donatello :)
