### ISSUE TITLE
How to make button group background and selector background from a custom drawable.

### ISSUE THREAD

**Issue by kusraevs** [ceryle/SegmentedButton#3]
Hello. Thank you for this cool library. I need to make gradient on button group background. Is there a way to do this now?

**Comment by ceryle** [comment]
Hi,
Thank you for the kind words. I updated the library, you can use "v1.1.2". I also added an example in sample project.

**Comment by kusraevs** [comment]
Well done! Thank you very much.

**Comment by ceryle** [comment]
You're welcome.
