### ISSUE TITLE
setPosition method missing..

### ISSUE THREAD

**Issue by afiqiqmal** [ceryle/SegmentedButton#5]
i found 2 issues here
1.  The setPosition method is missing when tried to use it. 
2. When i clicked, the button is switched. But when i hide and show the segmented button give original position, not the clicked position

**Comment by vinaywadhwa** [comment]
setPosition is missing indeed.

**Comment by vinaywadhwa** [comment]
created a merge request https://github.com/ceryle/SegmentedButton/pull/6

**Comment by ceryle** [comment]
Thank you vinaywadhwa. Sorry, I couldn't get your pull request. But I have updated the project. New version is v1.1.5 now.

**Comment by vinaywadhwa** [comment]
no worries. Thanks

**Comment by ceryle** [comment]
I have released a new version(v1.1.8) for the second problem. It should work now.
